math = false
author = "Gary Wei"
robots = "index, follow"

use_google_analytics = true
use_cronitor_analytics = true
use_pirsch_analytics = true

generate_date_on_footer = true

[external_links]
rel = "external noopener"
target = "_blank"

[social]
twitter = "garywei944" # used for twitter cards

[hugomods]
[hugomods.images]
modern_format = 'webp'

[image]
resample_filter = "Lanczos"
widths = [240, 360, 480, 720, 1080, 1440, 2160]
loading = "lazysizes"
render_hook = true
suppress_width_warning = true
