math = false
author = "Gary Wei"
robots = "index, follow"

use_google_analytics = true
use_pirsch_analytics = true

[external_links]
rel = "external noopener"
target = "_blank"

[social]
twitter = "garywei944" # used for twitter cards

[hugomods]
[hugomods.images]
modern_format = 'webp'

[responsive_images]
sizes = [1440, 768, 480]
