name: Hugo Build and Deploy to AWS

on:
  push:
    # Runs on pushes targeting the default branch
    branches:
      - deploy
  pull_request:
    branches:
      - deploy

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build and Deploy job
  deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.165.0
    steps:
      - uses: actions/checkout@v4
        with:
          ref: deploy
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true
      - uses: actions/cache@v4
        with:
          path: /home/runner/.cache/hugo_cache # <-- with hugo version v0.116.0 and above
          # path: /tmp/hugo_cache                 # <-- with hugo version < v0.116.0
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: Build
        run: hugo --gc --minify -e production --panicOnWarning

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync to s3
        run: aws s3 sync public "s3://$AWS_S3_BUCKET" --acl public-read --follow-symlinks --delete --no-progress
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

      - name: Invalidate cloudfront
        run: aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION" --paths '/*'
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
